# Generated by Django 5.2.1 on 2025-05-21 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.CharField(max_length=50, unique=True, verbose_name='Номер станка')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('installation_date', models.DateField(verbose_name='Дата установки')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Дата последнего ТО')),
            ],
            options={
                'verbose_name': 'Станок',
                'verbose_name_plural': 'Станки',
            },
        ),
        migrations.CreateModel(
            name='MachineOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя оператора')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Табельный номер')),
                ('qualification', models.CharField(max_length=100, verbose_name='Квалификация')),
            ],
            options={
                'verbose_name': 'Оператор',
                'verbose_name_plural': 'Операторы',
            },
        ),
        migrations.CreateModel(
            name='MachineSpecification',
            fields=[
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='machines_app.machine', verbose_name='Станок')),
                ('max_vibration', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Макс. вибрация')),
                ('max_power', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Макс. мощность')),
                ('max_temperature', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Макс. температура')),
                ('recommended_power', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Реком. мощность')),
            ],
            options={
                'verbose_name': 'Технические характеристики станка',
                'verbose_name_plural': 'Технические характеристики станков',
            },
        ),
        migrations.CreateModel(
            name='MachineReading',
            fields=[
                ('reading_number', models.AutoField(primary_key=True, serialize=False, verbose_name='№ показания')),
                ('timestamp', models.DateTimeField(verbose_name='Дата и время')),
                ('vibration_frequency', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Частота вибрации')),
                ('power_consumption', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Потребляемая мощность')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Температура')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines_app.machine', verbose_name='Станок')),
            ],
            options={
                'verbose_name': 'Показание станка',
                'verbose_name_plural': 'Показания станков',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MachineOperatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField(verbose_name='Дата назначения')),
                ('is_current', models.BooleanField(default=True, verbose_name='Текущее назначение')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines_app.machine', verbose_name='Станок')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines_app.machineoperator', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Назначение оператора',
                'verbose_name_plural': 'Назначения операторов',
                'unique_together': {('machine', 'operator', 'assignment_date')},
            },
        ),
    ]
