# Generated by Django 5.2.1 on 2025-05-24 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name': 'Светофор', 'verbose_name_plural': 'Светофоры'},
        ),
        migrations.AlterModelOptions(
            name='machineoperator',
            options={'verbose_name': 'Оператор светофора', 'verbose_name_plural': 'Операторы светофоров'},
        ),
        migrations.AlterModelOptions(
            name='machinereading',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Показание светофора', 'verbose_name_plural': 'Показания светофоров'},
        ),
        migrations.AlterModelOptions(
            name='machinespecification',
            options={'verbose_name': 'Технические характеристики светофора', 'verbose_name_plural': 'Технические характеристики светофоров'},
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер светофора'),
        ),
        migrations.AlterField(
            model_name='machineoperatorassignment',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines_app.machine', verbose_name='Светофор'),
        ),
        migrations.AlterField(
            model_name='machinereading',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines_app.machine', verbose_name='Светофор'),
        ),
        migrations.AlterField(
            model_name='machinereading',
            name='power_consumption',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоят'),
        ),
        migrations.AlterField(
            model_name='machinereading',
            name='vibration_frequency',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Проехало'),
        ),
        migrations.AlterField(
            model_name='machinespecification',
            name='machine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='machines_app.machine', verbose_name='Светофор'),
        ),
    ]
